var myFavPlaces = ["Dubai", "Ajman", "Abudhabi", "Sharjah", "America"];
console.log(myFavPlaces);
var myFavPlacesSorted = myFavPlaces.slice().sort();
console.log(myFavPlacesSorted);
console.log(myFavPlaces);
var myFavPlacesReverse = myFavPlaces.slice().reverse();
console.log(myFavPlacesReverse);
console.log(myFavPlaces);
myFavPlaces.reverse();
console.log(myFavPlaces);
myFavPlaces.reverse();
console.log(myFavPlaces);
myFavPlaces.sort();
console.log(myFavPlaces);
myFavPlaces.reverse();
console.log(myFavPlaces);
